// Package probes registers all built-in probe implementations.
//
// Import this package for side effects to populate the global probe registry:
//
//	import _ "github.com/praetorian-inc/augustus/pkg/register/probes"
package probes

import (
	_ "github.com/praetorian-inc/augustus/internal/probes/advpatch"
	_ "github.com/praetorian-inc/augustus/internal/probes/ansiescape"
	_ "github.com/praetorian-inc/augustus/internal/probes/apikey"
	_ "github.com/praetorian-inc/augustus/internal/probes/artprompts"
	_ "github.com/praetorian-inc/augustus/internal/probes/autodan"
	_ "github.com/praetorian-inc/augustus/internal/probes/avspamscanning"
	_ "github.com/praetorian-inc/augustus/internal/probes/badchars"
	_ "github.com/praetorian-inc/augustus/internal/probes/browsing"
	_ "github.com/praetorian-inc/augustus/internal/probes/continuation"
	_ "github.com/praetorian-inc/augustus/internal/probes/dan"
	_ "github.com/praetorian-inc/augustus/internal/probes/divergence"
	_ "github.com/praetorian-inc/augustus/internal/probes/donotanswer"
	_ "github.com/praetorian-inc/augustus/internal/probes/dra"
	_ "github.com/praetorian-inc/augustus/internal/probes/exploitation"
	_ "github.com/praetorian-inc/augustus/internal/probes/flipattack"
	_ "github.com/praetorian-inc/augustus/internal/probes/gcg"
	_ "github.com/praetorian-inc/augustus/internal/probes/glitch"
	_ "github.com/praetorian-inc/augustus/internal/probes/goodside"
	_ "github.com/praetorian-inc/augustus/internal/probes/grandma"
	_ "github.com/praetorian-inc/augustus/internal/probes/guardrail"
	_ "github.com/praetorian-inc/augustus/internal/probes/latentinjection"
	_ "github.com/praetorian-inc/augustus/internal/probes/leakreplay"
	_ "github.com/praetorian-inc/augustus/internal/probes/lmrc"
	_ "github.com/praetorian-inc/augustus/internal/probes/malwaregen"
	_ "github.com/praetorian-inc/augustus/internal/probes/misleading"
	_ "github.com/praetorian-inc/augustus/internal/probes/multiagent"
	_ "github.com/praetorian-inc/augustus/internal/probes/obscureprompt"
	_ "github.com/praetorian-inc/augustus/internal/probes/packagehallucination"
	_ "github.com/praetorian-inc/augustus/internal/probes/pair"
	_ "github.com/praetorian-inc/augustus/internal/probes/phrasing"
	_ "github.com/praetorian-inc/augustus/internal/probes/poetry"
	_ "github.com/praetorian-inc/augustus/internal/probes/prefix"
	_ "github.com/praetorian-inc/augustus/internal/probes/promptinject"
	_ "github.com/praetorian-inc/augustus/internal/probes/ragpoisoning"
	_ "github.com/praetorian-inc/augustus/internal/probes/realtoxicityprompts"
	_ "github.com/praetorian-inc/augustus/internal/probes/snowball"
	_ "github.com/praetorian-inc/augustus/internal/probes/suffix"
	_ "github.com/praetorian-inc/augustus/internal/probes/tap"
	_ "github.com/praetorian-inc/augustus/internal/probes/test"
	_ "github.com/praetorian-inc/augustus/internal/probes/treesearch"
	_ "github.com/praetorian-inc/augustus/internal/probes/webinjection"
)
