// Package detectors registers all built-in detector implementations.
//
// Import this package for side effects to populate the global detector registry:
//
//	import _ "github.com/praetorian-inc/augustus/pkg/register/detectors"
package detectors

import (
	_ "github.com/praetorian-inc/augustus/internal/detectors/advpatch"
	_ "github.com/praetorian-inc/augustus/internal/detectors/agent"
	_ "github.com/praetorian-inc/augustus/internal/detectors/always"
	_ "github.com/praetorian-inc/augustus/internal/detectors/ansiescape"
	_ "github.com/praetorian-inc/augustus/internal/detectors/any"
	_ "github.com/praetorian-inc/augustus/internal/detectors/apikey"
	_ "github.com/praetorian-inc/augustus/internal/detectors/artprompts"
	_ "github.com/praetorian-inc/augustus/internal/detectors/base"
	_ "github.com/praetorian-inc/augustus/internal/detectors/continuation"
	_ "github.com/praetorian-inc/augustus/internal/detectors/dan"
	_ "github.com/praetorian-inc/augustus/internal/detectors/divergence"
	_ "github.com/praetorian-inc/augustus/internal/detectors/encoding"
	_ "github.com/praetorian-inc/augustus/internal/detectors/exploitation"
	_ "github.com/praetorian-inc/augustus/internal/detectors/fileformats"
	_ "github.com/praetorian-inc/augustus/internal/detectors/flipattack"
	_ "github.com/praetorian-inc/augustus/internal/detectors/goodside"
	_ "github.com/praetorian-inc/augustus/internal/detectors/hijacking"
	_ "github.com/praetorian-inc/augustus/internal/detectors/judge"
	_ "github.com/praetorian-inc/augustus/internal/detectors/knownbadsignatures"
	_ "github.com/praetorian-inc/augustus/internal/detectors/latentinjection"
	_ "github.com/praetorian-inc/augustus/internal/detectors/leakreplay"
	_ "github.com/praetorian-inc/augustus/internal/detectors/lmrc"
	_ "github.com/praetorian-inc/augustus/internal/detectors/malwaregen"
	_ "github.com/praetorian-inc/augustus/internal/detectors/misleading"
	_ "github.com/praetorian-inc/augustus/internal/detectors/mitigation"
	_ "github.com/praetorian-inc/augustus/internal/detectors/multiagent"
	_ "github.com/praetorian-inc/augustus/internal/detectors/packagehallucination"
	_ "github.com/praetorian-inc/augustus/internal/detectors/pair"
	_ "github.com/praetorian-inc/augustus/internal/detectors/patterns"
	_ "github.com/praetorian-inc/augustus/internal/detectors/perspective"
	_ "github.com/praetorian-inc/augustus/internal/detectors/productkey"
	_ "github.com/praetorian-inc/augustus/internal/detectors/promptinject"
	_ "github.com/praetorian-inc/augustus/internal/detectors/ragpoison"
	_ "github.com/praetorian-inc/augustus/internal/detectors/ragpoisoning"
	_ "github.com/praetorian-inc/augustus/internal/detectors/shields"
	_ "github.com/praetorian-inc/augustus/internal/detectors/snowball"
	_ "github.com/praetorian-inc/augustus/internal/detectors/tap"
	_ "github.com/praetorian-inc/augustus/internal/detectors/toxiccomment"
	_ "github.com/praetorian-inc/augustus/internal/detectors/unsafecontent"
	_ "github.com/praetorian-inc/augustus/internal/detectors/visualjailbreak"
	_ "github.com/praetorian-inc/augustus/internal/detectors/webinjection"
)
