//go:build ignore

// gen_caps.go generates hooked_caps_gen.go: the power-set of combination
// wrappers that let HookedGenerator preserve whichever OPTIONAL generator
// interfaces its inner generator implements.
//
// Go cannot fabricate, at runtime, a type that satisfies an arbitrary subset of
// interfaces, so a decorator like HookedGenerator otherwise silently hides the
// inner generator's optional capabilities (ToolInvoker, MCPReconnaissance,
// VisionCapable, DocumentCapable, RawResponseProvider). The accepted fix is to
// generate one wrapper per non-empty subset (2^N-1 of them) and pick the right
// one by a capability bitmask. This keeps the approach interface-count-agnostic:
// to add a capability, add one entry to caps below and re-run `go generate`.
//
// Run: go generate ./pkg/hooks/...
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

type method struct {
	sig  string
	body string
}

type capability struct {
	// name is a short identifier used only in generated comments.
	name string
	// bitConst is the exported-within-package constant name for this bit.
	bitConst string
	// iface is the interface type expression, used for the type-assertion in
	// capMask and the compile-time assertions.
	iface string
	// methods are the interface's methods, forwarded by every wrapper whose mask
	// includes this capability.
	methods []method
}

// caps is the single source of truth. Bit i is 1<<i in mask order.
var caps = []capability{
	{
		name:     "ToolInvoker",
		bitConst: "capToolInvoker",
		iface:    "types.ToolInvoker",
		methods: []method{
			{"ListTools(ctx context.Context) ([]map[string]any, error)", "return hookedListTools(h.HookedGenerator, ctx)"},
			{"CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error)", "return hookedCallTool(h.HookedGenerator, ctx, name, args)"},
		},
	},
	{
		name:     "MCPReconnaissance",
		bitConst: "capMCPRecon",
		iface:    "types.MCPReconnaissance",
		methods: []method{
			{"MCPInventory(ctx context.Context) (*types.MCPInventory, error)", "return hookedMCPInventory(h.HookedGenerator, ctx)"},
		},
	},
	{
		name:     "VisionCapable",
		bitConst: "capVision",
		iface:    "types.VisionCapable",
		methods: []method{
			{"SupportsVision() bool", "return h.inner.(types.VisionCapable).SupportsVision()"},
		},
	},
	{
		name:     "DocumentCapable",
		bitConst: "capDocument",
		iface:    "types.DocumentCapable",
		methods: []method{
			{"SupportsDocuments() bool", "return h.inner.(types.DocumentCapable).SupportsDocuments()"},
		},
	},
	{
		name:     "RawResponseProvider",
		bitConst: "capRawResponse",
		iface:    "RawResponseProvider",
		methods: []method{
			{"LastRawResponse() []byte", "return h.inner.(RawResponseProvider).LastRawResponse()"},
		},
	},
}

func main() {
	var b bytes.Buffer

	fmt.Fprint(&b, `// Code generated by gen_caps.go; DO NOT EDIT.
// Run "go generate ./pkg/hooks/..." to regenerate.

package hooks

import (
	"context"

	"github.com/praetorian-inc/augustus/pkg/types"
)

`)

	// Capability bit constants.
	fmt.Fprintln(&b, "const (")
	for i, c := range caps {
		fmt.Fprintf(&b, "\t%s = 1 << %d // %s\n", c.bitConst, i, c.iface)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	// capMask reports which optional interfaces inner implements.
	fmt.Fprintln(&b, "// capMask reports the set of optional interfaces inner implements, as a bitmask.")
	fmt.Fprintln(&b, "func capMask(inner types.Generator) int {")
	fmt.Fprintln(&b, "\tmask := 0")
	for _, c := range caps {
		fmt.Fprintf(&b, "\tif _, ok := inner.(%s); ok {\n\t\tmask |= %s\n\t}\n", c.iface, c.bitConst)
	}
	fmt.Fprintln(&b, "\treturn mask")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	n := len(caps)
	total := 1 << n

	// wrapCaps returns the wrapper exposing exactly the interfaces in mask.
	fmt.Fprintln(&b, "// wrapCaps returns a generator that wraps base and additionally exposes exactly")
	fmt.Fprintln(&b, "// the optional interfaces named by mask. mask 0 (a plain generator) returns base")
	fmt.Fprintln(&b, "// unwrapped so it does not falsely advertise any optional interface.")
	fmt.Fprintln(&b, "func wrapCaps(base *HookedGenerator, mask int) types.Generator {")
	fmt.Fprintln(&b, "\tswitch mask {")
	fmt.Fprintln(&b, "\tcase 0:")
	fmt.Fprintln(&b, "\t\treturn base")
	for m := 1; m < total; m++ {
		fmt.Fprintf(&b, "\tcase %d:\n\t\treturn &%s{base}\n", m, structName(m))
	}
	fmt.Fprintln(&b, "\tdefault:")
	fmt.Fprintln(&b, "\t\treturn base")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	// One struct + methods + assertion per non-empty subset.
	for m := 1; m < total; m++ {
		sn := structName(m)
		fmt.Fprintf(&b, "// %s wraps HookedGenerator exposing: %s.\n", sn, strings.Join(ifaceNames(m), ", "))
		fmt.Fprintf(&b, "type %s struct{ *HookedGenerator }\n\n", sn)
		for i, c := range caps {
			if m&(1<<i) == 0 {
				continue
			}
			for _, mm := range c.methods {
				fmt.Fprintf(&b, "func (h *%s) %s { %s }\n", sn, mm.sig, mm.body)
			}
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "var (")
		for i, c := range caps {
			if m&(1<<i) == 0 {
				continue
			}
			fmt.Fprintf(&b, "\t_ %s = (*%s)(nil)\n", c.iface, sn)
		}
		fmt.Fprintln(&b, ")")
		fmt.Fprintln(&b)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("gofmt generated source: %v\n---\n%s", err, b.String())
	}
	if err := os.WriteFile("hooked_caps_gen.go", src, 0o644); err != nil {
		log.Fatalf("write hooked_caps_gen.go: %v", err)
	}
}

// structName returns the wrapper type name for a mask, encoding the set bits so
// the name is stable and unique (e.g. mask 5 -> hookedGen_TI_V).
func structName(mask int) string {
	var parts []string
	for i, c := range caps {
		if mask&(1<<i) != 0 {
			parts = append(parts, abbrev(c.name))
		}
	}
	return "hookedGen_" + strings.Join(parts, "_")
}

func ifaceNames(mask int) []string {
	var out []string
	for i, c := range caps {
		if mask&(1<<i) != 0 {
			out = append(out, c.iface)
		}
	}
	return out
}

// abbrev derives a short token from a capability name for struct naming.
func abbrev(name string) string {
	switch name {
	case "ToolInvoker":
		return "TI"
	case "MCPReconnaissance":
		return "MR"
	case "VisionCapable":
		return "V"
	case "DocumentCapable":
		return "D"
	case "RawResponseProvider":
		return "RR"
	default:
		return name
	}
}
