// Code generated by gen_caps.go; DO NOT EDIT.
// Run "go generate ./pkg/hooks/..." to regenerate.

package hooks

import (
	"context"

	"github.com/praetorian-inc/augustus/pkg/types"
)

const (
	capToolInvoker = 1 << 0 // types.ToolInvoker
	capMCPRecon    = 1 << 1 // types.MCPReconnaissance
	capVision      = 1 << 2 // types.VisionCapable
	capDocument    = 1 << 3 // types.DocumentCapable
	capRawResponse = 1 << 4 // RawResponseProvider
)

// capMask reports the set of optional interfaces inner implements, as a bitmask.
func capMask(inner types.Generator) int {
	mask := 0
	if _, ok := inner.(types.ToolInvoker); ok {
		mask |= capToolInvoker
	}
	if _, ok := inner.(types.MCPReconnaissance); ok {
		mask |= capMCPRecon
	}
	if _, ok := inner.(types.VisionCapable); ok {
		mask |= capVision
	}
	if _, ok := inner.(types.DocumentCapable); ok {
		mask |= capDocument
	}
	if _, ok := inner.(RawResponseProvider); ok {
		mask |= capRawResponse
	}
	return mask
}

// wrapCaps returns a generator that wraps base and additionally exposes exactly
// the optional interfaces named by mask. mask 0 (a plain generator) returns base
// unwrapped so it does not falsely advertise any optional interface.
func wrapCaps(base *HookedGenerator, mask int) types.Generator {
	switch mask {
	case 0:
		return base
	case 1:
		return &hookedGen_TI{base}
	case 2:
		return &hookedGen_MR{base}
	case 3:
		return &hookedGen_TI_MR{base}
	case 4:
		return &hookedGen_V{base}
	case 5:
		return &hookedGen_TI_V{base}
	case 6:
		return &hookedGen_MR_V{base}
	case 7:
		return &hookedGen_TI_MR_V{base}
	case 8:
		return &hookedGen_D{base}
	case 9:
		return &hookedGen_TI_D{base}
	case 10:
		return &hookedGen_MR_D{base}
	case 11:
		return &hookedGen_TI_MR_D{base}
	case 12:
		return &hookedGen_V_D{base}
	case 13:
		return &hookedGen_TI_V_D{base}
	case 14:
		return &hookedGen_MR_V_D{base}
	case 15:
		return &hookedGen_TI_MR_V_D{base}
	case 16:
		return &hookedGen_RR{base}
	case 17:
		return &hookedGen_TI_RR{base}
	case 18:
		return &hookedGen_MR_RR{base}
	case 19:
		return &hookedGen_TI_MR_RR{base}
	case 20:
		return &hookedGen_V_RR{base}
	case 21:
		return &hookedGen_TI_V_RR{base}
	case 22:
		return &hookedGen_MR_V_RR{base}
	case 23:
		return &hookedGen_TI_MR_V_RR{base}
	case 24:
		return &hookedGen_D_RR{base}
	case 25:
		return &hookedGen_TI_D_RR{base}
	case 26:
		return &hookedGen_MR_D_RR{base}
	case 27:
		return &hookedGen_TI_MR_D_RR{base}
	case 28:
		return &hookedGen_V_D_RR{base}
	case 29:
		return &hookedGen_TI_V_D_RR{base}
	case 30:
		return &hookedGen_MR_V_D_RR{base}
	case 31:
		return &hookedGen_TI_MR_V_D_RR{base}
	default:
		return base
	}
}

// hookedGen_TI wraps HookedGenerator exposing: types.ToolInvoker.
type hookedGen_TI struct{ *HookedGenerator }

func (h *hookedGen_TI) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}

var (
	_ types.ToolInvoker = (*hookedGen_TI)(nil)
)

// hookedGen_MR wraps HookedGenerator exposing: types.MCPReconnaissance.
type hookedGen_MR struct{ *HookedGenerator }

func (h *hookedGen_MR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR)(nil)
)

// hookedGen_TI_MR wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance.
type hookedGen_TI_MR struct{ *HookedGenerator }

func (h *hookedGen_TI_MR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR)(nil)
)

// hookedGen_V wraps HookedGenerator exposing: types.VisionCapable.
type hookedGen_V struct{ *HookedGenerator }

func (h *hookedGen_V) SupportsVision() bool { return h.inner.(types.VisionCapable).SupportsVision() }

var (
	_ types.VisionCapable = (*hookedGen_V)(nil)
)

// hookedGen_TI_V wraps HookedGenerator exposing: types.ToolInvoker, types.VisionCapable.
type hookedGen_TI_V struct{ *HookedGenerator }

func (h *hookedGen_TI_V) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_V) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_V) SupportsVision() bool { return h.inner.(types.VisionCapable).SupportsVision() }

var (
	_ types.ToolInvoker   = (*hookedGen_TI_V)(nil)
	_ types.VisionCapable = (*hookedGen_TI_V)(nil)
)

// hookedGen_MR_V wraps HookedGenerator exposing: types.MCPReconnaissance, types.VisionCapable.
type hookedGen_MR_V struct{ *HookedGenerator }

func (h *hookedGen_MR_V) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_V) SupportsVision() bool { return h.inner.(types.VisionCapable).SupportsVision() }

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_V)(nil)
	_ types.VisionCapable     = (*hookedGen_MR_V)(nil)
)

// hookedGen_TI_MR_V wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.VisionCapable.
type hookedGen_TI_MR_V struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_V) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_V) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_V)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_V)(nil)
	_ types.VisionCapable     = (*hookedGen_TI_MR_V)(nil)
)

// hookedGen_D wraps HookedGenerator exposing: types.DocumentCapable.
type hookedGen_D struct{ *HookedGenerator }

func (h *hookedGen_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.DocumentCapable = (*hookedGen_D)(nil)
)

// hookedGen_TI_D wraps HookedGenerator exposing: types.ToolInvoker, types.DocumentCapable.
type hookedGen_TI_D struct{ *HookedGenerator }

func (h *hookedGen_TI_D) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_D) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.ToolInvoker     = (*hookedGen_TI_D)(nil)
	_ types.DocumentCapable = (*hookedGen_TI_D)(nil)
)

// hookedGen_MR_D wraps HookedGenerator exposing: types.MCPReconnaissance, types.DocumentCapable.
type hookedGen_MR_D struct{ *HookedGenerator }

func (h *hookedGen_MR_D) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_D)(nil)
	_ types.DocumentCapable   = (*hookedGen_MR_D)(nil)
)

// hookedGen_TI_MR_D wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.DocumentCapable.
type hookedGen_TI_MR_D struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_D) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_D) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_D) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_D)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_D)(nil)
	_ types.DocumentCapable   = (*hookedGen_TI_MR_D)(nil)
)

// hookedGen_V_D wraps HookedGenerator exposing: types.VisionCapable, types.DocumentCapable.
type hookedGen_V_D struct{ *HookedGenerator }

func (h *hookedGen_V_D) SupportsVision() bool { return h.inner.(types.VisionCapable).SupportsVision() }
func (h *hookedGen_V_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.VisionCapable   = (*hookedGen_V_D)(nil)
	_ types.DocumentCapable = (*hookedGen_V_D)(nil)
)

// hookedGen_TI_V_D wraps HookedGenerator exposing: types.ToolInvoker, types.VisionCapable, types.DocumentCapable.
type hookedGen_TI_V_D struct{ *HookedGenerator }

func (h *hookedGen_TI_V_D) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_V_D) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_V_D) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_V_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.ToolInvoker     = (*hookedGen_TI_V_D)(nil)
	_ types.VisionCapable   = (*hookedGen_TI_V_D)(nil)
	_ types.DocumentCapable = (*hookedGen_TI_V_D)(nil)
)

// hookedGen_MR_V_D wraps HookedGenerator exposing: types.MCPReconnaissance, types.VisionCapable, types.DocumentCapable.
type hookedGen_MR_V_D struct{ *HookedGenerator }

func (h *hookedGen_MR_V_D) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_V_D) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_MR_V_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_V_D)(nil)
	_ types.VisionCapable     = (*hookedGen_MR_V_D)(nil)
	_ types.DocumentCapable   = (*hookedGen_MR_V_D)(nil)
)

// hookedGen_TI_MR_V_D wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.VisionCapable, types.DocumentCapable.
type hookedGen_TI_MR_V_D struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_V_D) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_D) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_V_D) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_D) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_MR_V_D) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_V_D)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_V_D)(nil)
	_ types.VisionCapable     = (*hookedGen_TI_MR_V_D)(nil)
	_ types.DocumentCapable   = (*hookedGen_TI_MR_V_D)(nil)
)

// hookedGen_RR wraps HookedGenerator exposing: RawResponseProvider.
type hookedGen_RR struct{ *HookedGenerator }

func (h *hookedGen_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ RawResponseProvider = (*hookedGen_RR)(nil)
)

// hookedGen_TI_RR wraps HookedGenerator exposing: types.ToolInvoker, RawResponseProvider.
type hookedGen_TI_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker   = (*hookedGen_TI_RR)(nil)
	_ RawResponseProvider = (*hookedGen_TI_RR)(nil)
)

// hookedGen_MR_RR wraps HookedGenerator exposing: types.MCPReconnaissance, RawResponseProvider.
type hookedGen_MR_RR struct{ *HookedGenerator }

func (h *hookedGen_MR_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_MR_RR)(nil)
)

// hookedGen_TI_MR_RR wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, RawResponseProvider.
type hookedGen_TI_MR_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_RR)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_TI_MR_RR)(nil)
)

// hookedGen_V_RR wraps HookedGenerator exposing: types.VisionCapable, RawResponseProvider.
type hookedGen_V_RR struct{ *HookedGenerator }

func (h *hookedGen_V_RR) SupportsVision() bool { return h.inner.(types.VisionCapable).SupportsVision() }
func (h *hookedGen_V_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.VisionCapable = (*hookedGen_V_RR)(nil)
	_ RawResponseProvider = (*hookedGen_V_RR)(nil)
)

// hookedGen_TI_V_RR wraps HookedGenerator exposing: types.ToolInvoker, types.VisionCapable, RawResponseProvider.
type hookedGen_TI_V_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_V_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_V_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_V_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_V_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker   = (*hookedGen_TI_V_RR)(nil)
	_ types.VisionCapable = (*hookedGen_TI_V_RR)(nil)
	_ RawResponseProvider = (*hookedGen_TI_V_RR)(nil)
)

// hookedGen_MR_V_RR wraps HookedGenerator exposing: types.MCPReconnaissance, types.VisionCapable, RawResponseProvider.
type hookedGen_MR_V_RR struct{ *HookedGenerator }

func (h *hookedGen_MR_V_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_V_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_MR_V_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_V_RR)(nil)
	_ types.VisionCapable     = (*hookedGen_MR_V_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_MR_V_RR)(nil)
)

// hookedGen_TI_MR_V_RR wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.VisionCapable, RawResponseProvider.
type hookedGen_TI_MR_V_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_V_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_V_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_MR_V_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_V_RR)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_V_RR)(nil)
	_ types.VisionCapable     = (*hookedGen_TI_MR_V_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_TI_MR_V_RR)(nil)
)

// hookedGen_D_RR wraps HookedGenerator exposing: types.DocumentCapable, RawResponseProvider.
type hookedGen_D_RR struct{ *HookedGenerator }

func (h *hookedGen_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.DocumentCapable = (*hookedGen_D_RR)(nil)
	_ RawResponseProvider   = (*hookedGen_D_RR)(nil)
)

// hookedGen_TI_D_RR wraps HookedGenerator exposing: types.ToolInvoker, types.DocumentCapable, RawResponseProvider.
type hookedGen_TI_D_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_D_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_D_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_TI_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker     = (*hookedGen_TI_D_RR)(nil)
	_ types.DocumentCapable = (*hookedGen_TI_D_RR)(nil)
	_ RawResponseProvider   = (*hookedGen_TI_D_RR)(nil)
)

// hookedGen_MR_D_RR wraps HookedGenerator exposing: types.MCPReconnaissance, types.DocumentCapable, RawResponseProvider.
type hookedGen_MR_D_RR struct{ *HookedGenerator }

func (h *hookedGen_MR_D_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_MR_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_D_RR)(nil)
	_ types.DocumentCapable   = (*hookedGen_MR_D_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_MR_D_RR)(nil)
)

// hookedGen_TI_MR_D_RR wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.DocumentCapable, RawResponseProvider.
type hookedGen_TI_MR_D_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_D_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_D_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_D_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_TI_MR_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_D_RR)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_D_RR)(nil)
	_ types.DocumentCapable   = (*hookedGen_TI_MR_D_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_TI_MR_D_RR)(nil)
)

// hookedGen_V_D_RR wraps HookedGenerator exposing: types.VisionCapable, types.DocumentCapable, RawResponseProvider.
type hookedGen_V_D_RR struct{ *HookedGenerator }

func (h *hookedGen_V_D_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_V_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_V_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.VisionCapable   = (*hookedGen_V_D_RR)(nil)
	_ types.DocumentCapable = (*hookedGen_V_D_RR)(nil)
	_ RawResponseProvider   = (*hookedGen_V_D_RR)(nil)
)

// hookedGen_TI_V_D_RR wraps HookedGenerator exposing: types.ToolInvoker, types.VisionCapable, types.DocumentCapable, RawResponseProvider.
type hookedGen_TI_V_D_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_V_D_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_V_D_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_V_D_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_V_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_TI_V_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker     = (*hookedGen_TI_V_D_RR)(nil)
	_ types.VisionCapable   = (*hookedGen_TI_V_D_RR)(nil)
	_ types.DocumentCapable = (*hookedGen_TI_V_D_RR)(nil)
	_ RawResponseProvider   = (*hookedGen_TI_V_D_RR)(nil)
)

// hookedGen_MR_V_D_RR wraps HookedGenerator exposing: types.MCPReconnaissance, types.VisionCapable, types.DocumentCapable, RawResponseProvider.
type hookedGen_MR_V_D_RR struct{ *HookedGenerator }

func (h *hookedGen_MR_V_D_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_MR_V_D_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_MR_V_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_MR_V_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.MCPReconnaissance = (*hookedGen_MR_V_D_RR)(nil)
	_ types.VisionCapable     = (*hookedGen_MR_V_D_RR)(nil)
	_ types.DocumentCapable   = (*hookedGen_MR_V_D_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_MR_V_D_RR)(nil)
)

// hookedGen_TI_MR_V_D_RR wraps HookedGenerator exposing: types.ToolInvoker, types.MCPReconnaissance, types.VisionCapable, types.DocumentCapable, RawResponseProvider.
type hookedGen_TI_MR_V_D_RR struct{ *HookedGenerator }

func (h *hookedGen_TI_MR_V_D_RR) ListTools(ctx context.Context) ([]map[string]any, error) {
	return hookedListTools(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_D_RR) CallTool(ctx context.Context, name string, args map[string]any) (types.ToolResult, error) {
	return hookedCallTool(h.HookedGenerator, ctx, name, args)
}
func (h *hookedGen_TI_MR_V_D_RR) MCPInventory(ctx context.Context) (*types.MCPInventory, error) {
	return hookedMCPInventory(h.HookedGenerator, ctx)
}
func (h *hookedGen_TI_MR_V_D_RR) SupportsVision() bool {
	return h.inner.(types.VisionCapable).SupportsVision()
}
func (h *hookedGen_TI_MR_V_D_RR) SupportsDocuments() bool {
	return h.inner.(types.DocumentCapable).SupportsDocuments()
}
func (h *hookedGen_TI_MR_V_D_RR) LastRawResponse() []byte {
	return h.inner.(RawResponseProvider).LastRawResponse()
}

var (
	_ types.ToolInvoker       = (*hookedGen_TI_MR_V_D_RR)(nil)
	_ types.MCPReconnaissance = (*hookedGen_TI_MR_V_D_RR)(nil)
	_ types.VisionCapable     = (*hookedGen_TI_MR_V_D_RR)(nil)
	_ types.DocumentCapable   = (*hookedGen_TI_MR_V_D_RR)(nil)
	_ RawResponseProvider     = (*hookedGen_TI_MR_V_D_RR)(nil)
)
