// Command genregister regenerates the blank-import registry files under
// pkg/register/<type>/ from the contents of internal/<type>/.
//
// For each capability type it scans the immediate subdirectories of the
// corresponding internal/ directory and emits a blank import for every package
// that registers itself (i.e. calls <type>.Register(...)). Helper packages that
// do not register anything are skipped automatically.
//
// It is invoked via `go generate ./...` (see pkg/register/generate.go) or
// `make generate`.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// capability describes one registry type to generate.
type capability struct {
	pkgName  string // register package name, e.g. "detectors"
	singular string // singular noun for the doc comment, e.g. "detector"
}

// capabilities lists every registry type genregister maintains. Adding a new
// capability type is the only manual edit this tool ever needs.
var capabilities = []capability{
	{pkgName: "probes", singular: "probe"},
	{pkgName: "detectors", singular: "detector"},
	{pkgName: "generators", singular: "generator"},
	{pkgName: "buffs", singular: "buff"},
	{pkgName: "harnesses", singular: "harness"},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genregister: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := moduleRoot()
	if err != nil {
		return err
	}
	modulePath, err := modulePathOf(root)
	if err != nil {
		return err
	}

	for _, c := range capabilities {
		scanDir := filepath.Join(root, "internal", c.pkgName)
		names, err := registeredSubpackages(scanDir, c.registerPkgPath(modulePath))
		if err != nil {
			return err
		}

		importPaths := make([]string, len(names))
		for i, n := range names {
			importPaths[i] = modulePath + "/internal/" + c.pkgName + "/" + n
		}

		content, err := c.render(modulePath, importPaths)
		if err != nil {
			return err
		}

		outFile := filepath.Join(root, "pkg", "register", c.pkgName, c.pkgName+".go")
		if err := writeIfChanged(outFile, content); err != nil {
			return err
		}
	}
	return nil
}

// registerPkgPath is the import path of the global registry package a capability
// registers against, e.g. github.com/.../pkg/detectors.
func (c capability) registerPkgPath(modulePath string) string {
	return modulePath + "/pkg/" + c.pkgName
}

// render produces the formatted contents of the register file for c.
func (c capability) render(modulePath string, importPaths []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/genregister; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package %s registers all built-in %s implementations.\n", c.pkgName, c.singular)
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Import this package for side effects to populate the global %s registry:\n", c.singular)
	b.WriteString("//\n")
	fmt.Fprintf(&b, "//\timport _ \"%s/pkg/register/%s\"\n", modulePath, c.pkgName)
	fmt.Fprintf(&b, "package %s\n", c.pkgName)

	if len(importPaths) > 0 {
		b.WriteString("\nimport (\n")
		for _, p := range importPaths {
			fmt.Fprintf(&b, "\t_ %q\n", p)
		}
		b.WriteString(")\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format %s register file: %w", c.pkgName, err)
	}
	return formatted, nil
}

// writeIfChanged writes content to path only when it differs from the current
// file contents, avoiding needless mtime churn.
func writeIfChanged(path string, content []byte) error {
	// #nosec G304 -- path is derived from the module root and the fixed
	// capabilities table, never from external input.
	existing, err := os.ReadFile(filepath.Clean(path))
	if err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// moduleRoot walks up from the working directory to find the directory
// containing go.mod, so the tool resolves the same paths regardless of the
// directory from which `go generate` invokes it.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from working directory")
		}
		dir = parent
	}
}

// modulePathOf reads the module path from root/go.mod.
func modulePathOf(root string) (string, error) {
	// #nosec G304 -- root is the module root located via moduleRoot(), not
	// external input.
	data, err := os.ReadFile(filepath.Clean(filepath.Join(root, "go.mod")))
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if path, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(path), nil
		}
	}
	return "", fmt.Errorf("module path not found in go.mod")
}
