package main

import "testing"

func TestCapabilityRender(t *testing.T) {
	cap := capability{pkgName: "buffs", singular: "buff"}
	imports := []string{
		"example.com/mod/internal/buffs/aaa",
		"example.com/mod/internal/buffs/bbb",
	}

	got, err := cap.render("example.com/mod", imports)
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	want := `// Code generated by tools/genregister; DO NOT EDIT.

// Package buffs registers all built-in buff implementations.
//
// Import this package for side effects to populate the global buff registry:
//
//	import _ "example.com/mod/pkg/register/buffs"
package buffs

import (
	_ "example.com/mod/internal/buffs/aaa"
	_ "example.com/mod/internal/buffs/bbb"
)
`

	if string(got) != want {
		t.Fatalf("render mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
