name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci*'
      - 'Makefile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: praetorian-inc/public-workflows/.github/workflows/go-ci.yml@bcc4e1bef0ebb6768945d04601aa777eae6ab7c4  # v2.17.1
    permissions:
      contents: read
    with:
      build-cmd-path: ./cmd/augustus
      build-binary-name: augustus
    secrets: inherit
