name: External Contribution Notify

on:
  issues:
    types: [opened, assigned, closed]
  pull_request_target:
    types: [opened, assigned, closed]

jobs:
  notify:
    uses: praetorian-inc/public-workflows/.github/workflows/external-contrib-notify.yml@135c50049eeef6e664bd7ea4aacaa33118083e30  # v2.0.10
    secrets: inherit
